language: node_js
node_js:
  - "stable"
services:
  - postgresql
before_script:
  - npm i -g sequelize
  - sequelize db:create weconn-test
  - sequelize db:migrate
  - npm i -D coveralls 
script:
  - npm run test
after_success:
  - npm run coverage
  - npm run report-coverage
env:
  global:
    - NODE_ENV=localTest
