language: node_js
node_js:
  - stable
services:
  - postgresql
before_script:
  - psql -c 'create database weconnect_test;' -U postgres
  - sequelize db:migrate
  - npm i -D coveralls
script:
  - npm run test
after_success:
  - npm run coverage
  - npm run report-coverage
env:
  - NODE_ENV=localTest