language: node_js
node_js:
  - "stable"
services:
  - postgresql
before_script:
  - npm i -g sequelize-cli
  - psql -c "CREATE DATABASE Database4Test;" -U postgres
  - psql -c "CREATE USER andrew WITH PASSWORD 'postgres';" -U postgres
  - sequelize db:migrate
  - npm i -D coveralls 
script:
  - npm run test
after_success:
  - npm run coverage
  - npm run report-coverage
env:
  global:
    - NODE_ENV=test
